events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # Lokasi file utama dashboard web
        root /app;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        # Optimasi pembacaan data JSON dan berkas besar di server
        location ~* \.(json|xlsx|txt)$ {
            add_header Access-Control-Allow-Origin *;
            expires -1;
        }
    }
}