events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # 1. Menampilkan Website Dashboard Utama (Akses Publik)
        location / {
            root   /app;
            index  index.html;
        }

        # 2. PINTU KHUSUS ARSIP (Akses Terbatas dengan Password)
        location /arsip/ {
            alias /app/output/;
            autoindex on;             # Memunculkan daftar folder/file
            autoindex_exact_size off; # Ukuran file lebih mudah dibaca (KB/MB)
            autoindex_localtime on;   # Waktu sesuai zona server
            
            # --- TAMBAHKAN KODE IZIN CORS INI ---
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin' always;

            # Tangani preflight request dari browser
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin';
                return 204;
            }
            # ------------------------------------

            # Mengaktifkan Gembok Password
            auth_basic "Area Terbatas Tim PBJ Kobar";
            auth_basic_user_file /etc/nginx/.htpasswd;
        }
    }
}