events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # Hanya 1 aturan: Menampilkan semua file statis dari folder /app
        location / {
            root   /app;
            index  index.html;
        }
    }
}